[package]
edition = "2024"
name = "ble-node"
rust-version = "1.88"
version = "0.1.0"
build = "build.rs"
default-run = "aggregator"
autobins = false

[[bin]]
name = "sensor"
path = "src/bin/sensor.rs"
test = false

[[bin]]
name = "aggregator"
path = "src/bin/aggregator.rs"
test = false

[target.'cfg(target_os = "espidf")'.dependencies]
anyhow = "1.0.100"
esp-idf-svc = "0.52.1"
esp32-nimble = "0.12.0"
log = "0.4.28"
uuid = "1.18.1"

[build-dependencies]
embuild = { version = "0.33.1", features = ["espidf"] }

[patch.crates-io]
embuild = { path = "vendor/embuild" }

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = "s"
overflow-checks = false
